### ISSUE TITLE
Doubt in way of implemention of fourier coefficient (lumen_flow.fcs) file in pipe3d_RCR example

### ISSUE THREAD

**Issue by Panchal1810** [SimVascular/svFSI#107]
In lumen_flow.fcs, there are 16 Fourier coefficient given to form unsteady profile. I just take 16 coefficient and plot it again the time using folllowing equation 

`a0 + a1cos(w*t)+b1sin(w*t)+a2cos(2*w*t)+b2sin(2*w*t)+ .... upto 16 values`

But this profile coming completely different than time series profile given in lumen_inlet.flow.

So, Have I done any mistake while calculating unsteady profile using Fourier coefficient ?

**Comment by vvedula22** [comment]
@Panchal1810 Can you can test the FFT interpolation for the given profile using the interpolation code [here](https://github.com/vvedula22/useful_codes/tree/master/fft_interp). The code will provide you with the Fourier coefficients and the interpolated time series.

**Comment by Panchal1810** [comment]
Thank you, sir @vvedula22 . I will check it.
