### ISSUE TITLE
Doubt on how to enter more than one domain per mesh element

### ISSUE THREAD

**Issue by luigamo** [SimVascular/svFSI#111]
Hello, 

I am trying to introduce in the domain file in which the mesh elements to be stimulated are indicated, more than one domain per mesh element, in order to simulate cardiac arrhythmias. 
I have tried to enter it by putting a domain number, a space and another domain number. For example: 2 3. But this did not work. Is it possible to do what I am trying to do?

Thank you in advance.

Regards, 

Luisa Gavier.

**Comment by vvedula22** [comment]
Yes, it is possible to do it. Make sure that the domain IDs are space-separated and not tab-delimited. Please use the [SimTK](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=188&pluginname=phpBB) forum for these types of issues.
