### ISSUE TITLE
Code enhancements for cardiac mechanics benchmark

### ISSUE THREAD

**Issue by vvedula22** [SimVascular/svFSI#113]
On doing the cardiac mechanics benchmark exercise, we realized that we had to add/modify a few features in the code to obtain a reasonable agreement with the posted results. These include the treatment of the viscosity of solids, fiber directions, and some minor bugs in higher-order elements and the treatment of the Holzapfel-Ogden material model for the myocardium.

The following features are added to the code:

- Fiber directions are now generalized. Fibers can be stored at nodes, elements, or the Gauss quadrature points. The code will try to automatically figure out the type of fiber storage while reading the fiber direction file provided in the input file.

- Viscosity for solids is treated using two approaches:
    - Newtonian-fluid, where the Cauchy stress is linearly proportional to the deviatoric strain-rate tensor
    - Potential-based formulation, where the 2nd Piola-Kirchhoff stress is linearly proportional to the rate of change of Green-Lagrange deformation tensor
   
- Some minor bugs fixed include:
    - Setting shape function bounds for higher-order elements
    - Derivatives of the fiber-sheet interaction term in the Holzapfel-Ogden material model
- Viscosity-based stabilization is removed from ustruct to avoid unphysical deformations.

**Comment by ktbolt** [comment]
@vvedula22 Issues are used to inform other developers about changes to the current code base, bug fixes, added functionality, enhancements, etc.

It is of little use to other developers to open an Issue after making all of the code changes.

**Comment by vvedula22** [comment]
@ktbolt I agree with what you said. But this was one of those cases when we had less time, couldn't really figure out why we were seeing discrepancies in the benchmark tests, and had to quickly try various things without even knowing which one of them would work, and which among them would be integrated into the main repository.

**Comment by ktbolt** [comment]
@vvedula22 Well then an Issue should have been opened stating 
```
seeing discrepancies in the benchmark tests, testing to see what is going on.
```
and then new Issues opened when you discovered what the problems where and how you fixed them.

Other developers had no clue what you were doing and out of the blue there's 30 files that have been significantly modified. This does not follow the guidelines about how things are done in a collaborative code base. There are no cases for not following the guidelines.
