### ISSUE TITLE
The code does not build using gcc 10.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSI#23]
I pulled down the latest master branch and tried to build on MacOS 10.13.6 using using gcc 10.

I get lots of compile errors like
```

   59 |          CALL MPI_ALLREDUCE(u, uG, 1, mpreal, MPI_SUM, commu%comm, ierr)
      |                            2
......
   77 |          CALL MPI_ALLREDUCE(u, uG, n, mpreal, MPI_SUM, commu%comm, ierr)
      |                            1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
```
A workaround is setting the `-std=legacy` compiler flag.

**Comment by vvedula22** [comment]
The issue seems related to the fact that the Fortran compiler in gcc version 10.x has become stricter: some warnings have turned out into errors. Could you try adding the option "-fallow-argument-mismatch" to the Fortran compiler options?

**Comment by vvedula22** [comment]
I am having another error with gcc-10 on Expanse cluster with CentOS 8 and openmpi/mvapich2:

/home/vedula/sw/svFSI/src/Code/Source/svFSI/COMU.f:252:21:
  252 |       CALL MPI_ABORT(cm, MPI_ERR_OTHER, ierr)
      |                     1
Error: Explicit interface required for polymorphic argument at (1)

Have you come across this before? Compiles fine with gcc-9.2.0.

**Comment by ktbolt** [comment]
I see the same error on MacOS, replaced `CALL MPI_ABORT(cm, MPI_ERR_OTHER, ierr)` with
```
CALL MPI_ABORT(cm%com(), MPI_ERR_OTHER, ierr)
```
and the code compiled fine.

**Comment by vvedula22** [comment]
Thanks. Now the code compiles fine on Mac or Clusters with newer gcc. 
Included these changes in a new commit and closing this issue.
