### ISSUE TITLE
 Computing average quantities fails

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSI#29]
When computing average results I set `Save averaged results: t`. At the end of the simulation I get the following error

```
Computing average quantities
              ERROR: could not find <FS_Velocity> in PointData attribute
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR occurred, see below for more explanation
ERROR: VTU file read error (point data)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Tested using the `01-Pipe_Flow` example.

**Comment by vvedula22** [comment]
I tested this and reproduced this bug. The bug has to do with associating an equation symbol with the variable name. This has been removed a while ago while writing vtu files but wasn't reflected in another subroutine READVTUS where the solution files are read to compute nodal averages.

Fixed this bug in a new commit and will shortly create a pull request.
