### ISSUE TITLE
Ramp function with three time steps

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#37]
I want to ramp a BC linearly between `>2` given time points, e.g.,
```
t   p
0.0 0.0
1.0 1.0
2.0 11.0
```
so that `p(t=0.5) = 0.5` and `p(t=1.5) = 6.0`.

Currently, for unsteady BCs, we have two options:
- `Temporal values file path` (**fluid**): do a periodic Fourier interpolation
https://github.com/SimVascular/svFSI/blob/8f4865a76dd20644f4c8701fd72f88a5c909c865/svFSI_master.inp#L830-L833
- `Ramp function` (**solid**): linearly ramp between the first and second value
https://github.com/SimVascular/svFSI/blob/8f4865a76dd20644f4c8701fd72f88a5c909c865/svFSI_master.inp#L844-L850

This explanation (and my failed attempts) suggest that we can currently only interpolate between exactly **two** time steps, but not more. @vvedula22 Is that correct or am I missing something?

**Comment by vvedula22** [comment]
@mrp089 No, we don't have a way to provide two ramps for the same BC.  Ramp is only provided between first two time points and thereafter, the value remains constant. The format for the unsteady BC file would then be,

```
<num_time_points>  <num_Fourier_modes>
<time_1>    <value_1>
<time_2>    <value_2>
```

If you really have to provide two ramps, you may do so by adding another unsteady BC and split the load between the two BCs such as,

BC 1:
```
t   p
0.0  0.0
1.0  1.0
```

BC 2:
```
t   p
1.0   0.0
2.0   10.0
```
As the load applied is additive, in BC 2, I have subtracted the load from BC 1. But, this may not apply to all cases such as applying Dirichlet BC.

**Comment by mrp089** [comment]
Thanks, @vvedula22! I think that workaround is okay for now
