### ISSUE TITLE
Store variables at Gauss point in each time step

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#38]
For G&R in #32 I need to store a couple of internal "history" variables (scalars and arrays) **on each Gauss point** and retrieve/update them in each time step. In C++ I would do this with class variables of a material subroutine instance.

I can store those variables within `GETPK2CC` in `MATMODELS.f` but that means they're initialized in every time step and not stored. @ktbolt @vvedula22 Do you have an idea where and how to best do this?

**Comment by ktbolt** [comment]
@mrp089 I think you will need to add your state variables to the `COMMOD` module defined in`MOD.f`. The `COMMOD` module is basically a container for global variables.

**Comment by vvedula22** [comment]
@mrp089 I did something similar for modeling soft tissue damage. As @ktbolt mentioned, you have to use modules in Fortran to access variables across subroutines and functions. For the damage model, 

- I defined a global damage model as,
[CONSTS.f](https://github.com/vvedula22/svFSI/blob/tissueDamage/Code/Source/svFSI/CONSTS.f#L191-L194)

- Parameters read from input file are stored in `TYPE stModelType`
[MOD.f](https://github.com/vvedula22/svFSI/blob/tissueDamage/Code/Source/svFSI/MOD.f#L120-L127)

- History variables stored at the integration point level are stored within `TYPE mshType` 
[MOD.f](https://github.com/vvedula22/svFSI/blob/tissueDamage/Code/Source/svFSI/MOD.f#L575-L580)

The history variables are allocated and stored only when the damage model is invoked by the user. Most of the code development for adding the damage model was done in the commit,

https://github.com/vvedula22/svFSI/commit/0091448b5a26434fbacc5e54c36ca057f2836510

In particular, you may review changes to the following codes:
```
For parameter and variable declaration
- CONSTS.f
- MOD.f

For reading parameters from the input file, distribution across processes, initialization, and deallocation,
- READFILES.f
- DISTRIBUTE.f
- INITIALIZE.f
- ALLFUN.f

For using damage variables to update solid stress, interface with material subroutines (`GETPK2CC`), and updating damage variables over time,
- STRUCT.f
- MATMODELS.f
- MAIN.f

For usage in post-processing,
- POST.f
```

**Comment by mrp089** [comment]
Awesome!! That was very helpful @ktbolt and @vvedula22!
