### ISSUE TITLE
Create make-based build system for svFSI

### ISSUE THREAD

**Issue by vvedula22** [SimVascular/svFSI#45]
`svSolver` currently supports `BuildWithMake` in addition to the CMake-based build system. However, the one adapted for `svFSI` does not work.

It will be useful to fix the `BuildWithMake` for `svFSI`. It is particularly convenient to have a make-based build system on clusters where users can easily set appropriate paths to libraries, compilers, etc. depending on the module environment, which are otherwise hard to set using CMake variables.

**Comment by ktbolt** [comment]
@vvedula22 I'd rather not have two build systems. If CMake is not working then let's fix it.
