### ISSUE TITLE
Pattern in uniform ring condition

### ISSUE THREAD

**Issue by schwarz-e** [SimVascular/svFSI#49]
In a simulation with uniform stress applied to the inner surface of a ring, the resulting stress calculated is not uniform along the circumference, and instead a harmonic pattern emerges. 

![image](https://user-images.githubusercontent.com/53580464/133327036-05039014-084b-40ff-ab68-67a9c5166fe4.png)

**Comment by vvedula22** [comment]
@schwarz-e The Stress you are plotting is the second Piola-Kirchhoff stress and you are plotting the `magnitude' (not sure how exactly it is defined in Paraview for a symmetric tensor). You might want to compute and plot radial and circumferential stresses to see expected results.
