### ISSUE TITLE
Some issues in svFSI/INSTALL.md

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSI#50]
In step 7

7. Download `svFSI` from GitHub:

```bash
mkdir svFSI-git
cd svFSI-git
git clone git@github.com:SimVascular/svFSI.git
mv svFSI/  src
```
I was unable to clone the repository with this command. Instead, I used
```bash
 git clone https://github.com/SimVascular/svFSI.git
```
Might be helpful to add this.

In step 8

8. Create a separate `build` folder and compile using the following commands:

```bash
mkdir build
cd build
ccmake ../
make
```
I believe the line should read
```bash
ccmake ../src
```

**Comment by vvedula22** [comment]
@aabrown100-git Thanks, will fix the typos. Reg. step 7, you need to set up `ssh` public key on your local machine and add it to your profile on GitHub to use `ssh` to clone a repository. This approach is more secure than `https` although `https` is easier as it is less likely to be blocked by the firewall or something.
