### ISSUE TITLE
Output GlobalNodeIds?

### ISSUE THREAD

**Issue by schwarz-e** [SimVascular/svFSI#53]
Is there currently a way to have svFSI include the GlobalNodeIds with the output vtu? It would be useful for post-processing which requires querying on specific, known points.

**Comment by vvedula22** [comment]
@schwarz-e  GlobalNodeIDs are defined for faces. The output vtu files have mesh coordinates in there for postprocessing. If you are processing faces and need GlobalNodeIDs, you may load them from the vtp files.
