### ISSUE TITLE
Holzapfel-Ogden model for myocardium: heaviside function approximation

### ISSUE THREAD

**Issue by LeiShi3374** [SimVascular/svFSI#55]
I will create a branch used for a benchmark problem.

A new material parameter k needs to be added to the constitutive model HO. It is in the equation of chi(x)=1/(1+exp(-k(x-1))) which is used to approximate the heaviside function in a "softer" way to calculate only the fiber stress in tension instead of the method used in the original codes which used a hard if-else function.

A higher k corresponds to a steeper approximation of the heaviside function.

I will work on this issue, verify and test it before pulling it.

**Comment by vvedula22** [comment]
Thanks - this will be useful for cardiac mechanics simulations. You should also add the simplified viscoelastic term to the strain energy and this feature should be added for both `struct` and `ustruct`. The modified strain energy would then depend on `\dot{E}` as shown below,

![temp](https://user-images.githubusercontent.com/17485535/134824661-e6355297-3577-488f-a57f-74e883dab4ab.png)

Please make sure these implementations are thoroughly tested before making a pull request.

**Comment by LeiShi3374** [comment]
Update: The implementation is working for STRUCT but are still figuring out issue with USTRUCT.

Here is a snapshot of the representative fully contracted volume.

![image](https://user-images.githubusercontent.com/69972309/136719185-8c1621c7-72d3-47e5-bcd2-b52ea85c6f06.png)

**Comment by LeiShi3374** [comment]
A macroscopic viscoelasticity has been implemented, with the second PK = \eta E_dot. \eta can be set using Viscosity under "Add equation" in both struct and ustruct. The default Viscosity is 0.

The Heaviside function is implemented for HO model and is approximated using a function \chi=\frac{1}{1+exp(-k(x-1))}. The default k is equal to 100 and can be set as a material parameter in HO model.

Test cases are uploaded in project svFSI-Tests

**Comment by vvedula22** [comment]
I am reopening this issue as there were further updates in pull request #60 
@LeiShi3374 can you add more details here on the new changes in this pull request?

**Comment by LeiShi3374** [comment]
Update: a modified HO model has been added based on "Nolan, David R., et al. "A robust anisotropic hyperelastic formulation for the modelling of soft tissue." Journal of the mechanical behavior of biomedical materials 39 (2014): 48-60." 

In this model, an unconstrained version of the HO model was implemented based on the full invariants instead of the isochoric invariants.

A bug in Robin boundary has been fixed. The bug was: when using ustruct equation and Robin boundary, the simulation was not converging.

**Comment by vvedula22** [comment]
Closing this issue now as the pull request #60 is now merged with master commit bb4b8c4ccc0e9f352799ced460dc3f21fcc3ea81
