### ISSUE TITLE
Inflow profile on quarter cylinder

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#59]
To impose symmetry boundary conditions, I'm running a quarter cylinder profile. Unfortunately, when I apply inflow conditions, all my cut-surfaces are treated as walls and I end up with zero velocity there:

![inflow_profile_quarter](https://user-images.githubusercontent.com/51269309/137825586-84f87571-2deb-48d4-883a-50746a861766.png)

It's fine in the interior of the domain: The velocity vectors on the cur-offs are all within the cut planes.

To get around this problem, I thought I'd use the option `Profile: User_defined`. Unfortunately, I couldn't find an example that actually uses this option via `Spatial profile file path`. I'll try reconstructing it from `READFILES.f`...

@vvedula22 Do you have an example where this is used?

**Comment by mrp089** [comment]
Solved... The file looks like
```
GlobalNodeID_0 val_0
...
GlobalNodeID_n val_n
```
where `n` is the number of nodes on the boundary face.

**Comment by vvedula22** [comment]
@mrp089 Sorry for the delay. You could also use 'Effective direction' while setting the Dirichlet BCs to achieve symmetry where you set the flow value along a particular direction (z-direction in the above case). To get symmetry, you could also set another homogenous Dirichlet BC along the orthogonal directions. For e.g., set 0 values for x- and y- components on the vertical and horizontal planes. Using "User_defined" spatial profile might also work but it reads only a scalar value that is multiplied with the actual imposed value. You will not have fine control over the individual vector components using this approach.
