### ISSUE TITLE
Typo in svFSI_master.inp Robin BC

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSI#65]
To impose Robin BC in the normal direction, svFSI_master.inp says the command should be

Applied along normal direction: t

I believe the proper command is

Apply along normal direction: t

Since line 1750 of READFILES.f reads
lPtr => list%get(lBc%rbnN, "Apply along normal direction")

**Comment by vvedula22** [comment]
Fixed in pull req #96
