### ISSUE TITLE
Zero normal displacement BC implementation in svFSI

### ISSUE THREAD

**Issue by tshidhore** [SimVascular/svFSI#7]
**Is your feature request related to a problem? Please describe.**
For my patient-specific FSI simulations, I wish to specify zero normal displacement at the end caps of the geometry.

**Describe the solution you'd like**
A checkbox/flag option within the GUI to automatically implement the boundary condition along the face normal

**Describe alternatives you've considered**
Ability of svFSI to accept general effective directions so that the normal vectors may be provided manually.

**Comment by vvedula22** [comment]
Extended Robin BC to be able to handle normal direction (commit 464a6e2f4eb4eedd482952b242006d92c5fa2b5a). This represents a weak treatment of zero-normal displacement that depends on the spring constant and damping constant, which could be problem dependent. 

I am closing this issue as it was demonstrated to be working.
