### ISSUE TITLE
Use mesh scale factor for all outputs with length dimension

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSI#86]
It appears that when a mesh scale factor is used (for example to convert a mesh in micron units to meters), the geometry (nodal positions) and the displacements are scaled back to microns when a result.vtu file is written. However, acceleration and velocity are not scaled back, but retain meters as their unit of length. I'm not sure if this was intentional, but in my opinion this is inconsistent and confusing. If a mesh scale factor is used, I think all outputs with a dimension of length should be scaled back. This could easily be fixed by dividing by the mesh scale factor in lines 547 and 554 in VTKXML.f (in the function WRITEVTUS()).

**Comment by vvedula22** [comment]
@aabrown100-git Mesh scale factor need not always be used for unit conversion but sometimes could be used for pure geometric scaling. In that case, the user may not want to scale all the post-processing quantities. Ultimately, it is the user's responsibility to use a consistent unit system for the problem (mesh, equation parameters, etc.). 

We rescale the mesh back to the original dimensions in the vtu file to be consistent with the input. We didn't want to have a discrepancy between the input mesh and the results (vtu files).
