### ISSUE TITLE
Solid viscosity bug

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSI#95]
There appears to be a bug in the implementation of solid viscosity in both STRUCT and USTRUCT. As the value of viscosity increases, the convergence of the Newton iteration deteriorates or fails altogether. @vvedula22 @LeiShi3374  and I have been working on fixing this issue. The latest implementation can be found at this commit on Vijay's fork: https://github.com/vvedula22/svFSI/commit/a902e8f7611c82dc17a674c91e35a55ea0d751b3.

**Comment by vvedula22** [comment]
@aabrown100-git merged all these bug fixes to the main repo #96. Please continue testing the LPN coupling and update any issues.

**Comment by vvedula22** [comment]
Closing this issue as this appears to have been solved in #96
